FROM oven/bun:1.2-alpine AS deps
WORKDIR /app

COPY package.json bun.lockb* bun.lock ./
RUN bun install --frozen-lockfile


FROM node:22-alpine AS builder
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .


ARG BACKEND_URL
ARG API_URL
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_FRONTEND_URL
ARG NEXT_PUBLIC_BA_API_URL
ARG NEXT_PUBLIC_BA_BASE_PATH
ARG NEXT_PUBLIC_S3_URL


ENV BACKEND_URL=$BACKEND_URL
ENV API_URL=$API_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_FRONTEND_URL=$NEXT_PUBLIC_FRONTEND_URL
ENV NEXT_PUBLIC_BA_API_URL=$NEXT_PUBLIC_BA_API_URL
ENV NEXT_PUBLIC_BA_BASE_PATH=$NEXT_PUBLIC_BA_BASE_PATH
ENV NEXT_PUBLIC_S3_URL=$NEXT_PUBLIC_S3_URL
ENV NEXT_TELEMETRY_DISABLED=1

RUN npm run build
FROM node:22-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs
EXPOSE 3000

CMD ["node", "server.js"]
